DATABASE_URL = "postgresql://neondb_owner:npg_NDvSeJBcmR90@ep-orange-sound-atzgb0cz-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"


CLOUDINARY_CLOUD_NAME = "dl5zh5l0q"
CLOUDINARY_API_KEY = "875939854233121"
CLOUDINARY_API_SECRET = "UZhEN9blfQEVJBVh5HVbWQrq0c8"